kind: Deployment
apiVersion: apps/v1
metadata:
  name: api2
  namespace: example
  labels:
    app.kubernetes.io/name: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api2
    spec:
      containers:
        - name: api2
          image: registry.kthcloud.com/examples/api2-example
---
kind: Service
apiVersion: v1
metadata:
  name: api2
  namespace: example
  labels:
    app.kubernetes.io/name: api2
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: api2